/**
 * MLP Core Types
 * These types define the protocol. Storage adapters, embedding adapters,
 * and any future language port must honour these contracts.
 */

// ─── Cluster ─────────────────────────────────────────────────────────────────

/**
 * A Cluster is the atomic unit of memory in MLP.
 * It encodes not just what was decided, but why, when, and how it connects.
 */
export interface Cluster {
  id: string;

  /** What was decided or established. One or two sentences max. */
  summary: string;

  /** The intent behind the decision. Why does this exist? */
  intent: string;

  /** The reasoning. What led to this? What was considered? */
  rationale: string;

  /** Domain scopes this cluster — e.g. "product", "engineering", "ops" */
  domain: string;

  /** Tags for fast filtering before activation spreads */
  tags: string[];

  /** When this cluster was encoded. ISO 8601. */
  timestamp: string;

  /**
   * Strength reflects how often this cluster has been activated.
   * Starts at 1.0. Grows via Hebbian reinforcement.
   */
  strength: number;

  /**
   * Embedding vector — generated by whichever EmbeddingAdapter is configured.
   * Stored as flat number array. Dimension depends on the model used.
   */
  embedding?: number[];
}

// ─── Connection ───────────────────────────────────────────────────────────────

/**
 * A weighted directed edge between two clusters.
 * Weight strengthens when both clusters are co-activated (Hebbian rule).
 */
export interface Connection {
  fromId: string;
  toId: string;

  /** Describes the relationship — e.g. "requires", "extends", "contradicts" */
  relationshipType: string;

  /** Starts at 1.0. Grows with co-activation. Never decays in v1. */
  weight: number;

  /** Total number of times this connection has been traversed */
  activations: number;
}

// ─── Activation Result ────────────────────────────────────────────────────────

/**
 * What activate_memory returns.
 * A ranked set of clusters surfaced by the query, with activation scores.
 */
export interface ActivationResult {
  /** The clusters surfaced, ordered by activation score descending */
  clusters: ActivatedCluster[];

  /** The original query that triggered activation */
  query: string;

  /** How many degrees the activation spread before stopping */
  degreesTraversed: number;

  /** Total clusters considered during spreading */
  clustersConsidered: number;
}

export interface ActivatedCluster extends Cluster {
  /** Composite score: vector similarity × connection weight × cluster strength */
  activationScore: number;

  /** How many hops from the seed cluster */
  distance: number;
}

// ─── Input Types ──────────────────────────────────────────────────────────────

/**
 * Raw input to encode_memory.
 * The encoder extracts Cluster dimensions from this.
 */
export interface EncodeInput {
  /** Raw content — could be a decision, a conversation, a document, a note */
  content: string;

  /** Optional hint to the encoder about which domain this belongs to */
  domain?: string;

  /** Optional tags to attach. Encoder may add more. */
  tags?: string[];

  /**
   * Optional IDs of clusters this should connect to.
   * If omitted, the encoder finds connections via vector similarity.
   */
  connectTo?: string[];
}

/**
 * Input to activate_memory.
 */
export interface ActivateInput {
  /** Natural language query — what the tool or person is asking for */
  query: string;

  /** Optional domain filter — narrows activation to one domain */
  domain?: string;

  /** Max degrees to spread. Default 6 (Watts small-world boundary). */
  maxDegrees?: number;

  /** Max clusters to return. Default 10. */
  topK?: number;
}

/**
 * Input to strengthen_connection.
 */
export interface StrengthenInput {
  fromId: string;
  toId: string;

  /** How much to add to the weight. Default 0.2. */
  delta?: number;
}
